#!/bin/bash


echo -e "------------------------ \e[032;1mRUBAH TANGGAL EXPIRED\e[0m ------------------------"
echo -e "                       \e[032;1mALL SUPPORTED ALIYA HAURA\e[0m"
echo -e "                 \e[032;1mhttps://www.facebook.com/aliyahaura02\e[0m"
echo -e "        \e[032;1mCONTACT SUPPORT Telegram @aliyahaura02 SMS/WA 089697708638\e[0m"
echo "-------------------------------"
echo "USERNAME          EXP DATE     "
echo "-------------------------------"
while read expired
do
        AKUN="$(echo $expired | cut -d: -f1)"
        ID="$(echo $expired | grep -v nobody | cut -d: -f3)"
        exp="$(chage -l $AKUN | grep "Account expires" | awk -F": " '{print $2}')"
        if [[ $ID -ge 1000 ]]; then
        printf "%-17s %2s\n" "$AKUN" "$exp"
        fi
done < /etc/passwd
echo "-------------------------------"
echo -e "\e[032;1mScript Modified by Aliya haura\e[0m"
echo "-------------------------------"
read -p "Isikan username: " uname
read -p "Isikan Tanggal Expire (TH-BLN-TGL): " expdate
read -p "Anda Akan Merubah Tanggal Expire SSH/OpenVPN Username $uname [y/n]:" -e -i y useradd
if [ $useradd = 'y' ]; then
usermod -e $expdate $uname
exp="$(chage -l $uname | grep "Account expires" | awk -F": " '{print $2}')"
echo "Rubah Tanggal Expire Username $uname Berhasil"
echo "-----------------------------------
Data Login SSH:
-----------------------------------
Host/IP: $MYIP
Dropbear Port: 443, 80
OpenSSH Port:  143
Squid Proxy: 8000, 8080, 3128
OpenVPN Config: http://$MYIP:81/client.ovpn
Username  : $uname
Valid s/d : $exp
-----------------------------------
Terimakasih dan Selamat Menggunakan
-----------------------------------"
else
if [ $useradd = 'n' ]; then
echo "Batal Rubah Tanggal Expire Username $uname"
fi
fi
exit 1
cd ~/