#!/bin/bash

echo -e "------------------------\e[032;1mGENERATE  AKUN SSH\e[0m------------------------"
echo -e "                    \e[032;1mALL SUPPORTED ALIYA HAURA\e[0m"
echo -e "              \e[032;1mhttps://www.facebook.com/aliyahaura02\e[0m"
echo -e "     \e[032;1mCONTACT SUPPORT Telegram @aliya hauraSMS/WA 089697708638\e[0m"

echo ""

read -p "Berapa jumlah akun yang akan dibuat: " JUMLAH
read -p "Berapa hari akun aktif: " AKTIF

today="$(date +"%Y-%m-%d")"
expire=$(date -d "$AKTIF days" +"%Y-%m-%d")

echo ""
echo "-----------------------------------"
echo "Data Login:"
echo "-----------------------------------"
echo "Host/IP: $MYIP"
echo "Dropbear Port: 443, 22, 80"
echo "OpenSSH Port: 110, 143"
echo "Squid Proxy: 8000, 8080, 3128"
echo "OpenVPN Config: http://$MYIP:81/client.ovpn"

for (( i=1; i <= $JUMLAH; i++ ))
do
	username=`cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 15 | head -n 1`;
	useradd -M -N -s /bin/false -e $expire $username
	#password=`cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 15 | head -n 1`;
	echo $username:$username | chpasswd
	
	echo "$i. Username/Password: $username"
done

echo "Valid s/d: $(date -d "$AKTIF days" +"%d-%m-%Y")"
echo "-----------------------------------"

cd ~/
