#!/bin/bash

echo "-----------------------------------"
echo "USERNAME              EXP DATE     "
echo "-----------------------------------"

while read expired
do
	AKUN="$(echo $expired | cut -d: -f1)"
	ID="$(echo $expired | grep -v nobody | cut -d: -f3)"
	exp="$(chage -l $AKUN | grep "Account expires" | awk -F": " '{print $2}')"
	if [[ $ID -ge 1000 ]]; then
		printf "%-21s %2s\n" "$AKUN" "$exp"
	fi
done < /etc/passwd

JUMLAH="$(awk -F: '$3 >= 1000 && $1 != "nobody" {print $1}' /etc/passwd | wc -l)"

echo "-----------------------------------"
echo "Jumlah akun: $JUMLAH user"
echo "-----------------------------------"
echo ""
echo "----------------------------------------------------------------"
echo -e "                       \e[032;1mALL SUPPORTED ALIYA HAURA\e[0m"
echo -e "                 \e[032;1mhttps://www.facebook.com/aliyahaura02\e[0m"
echo -e "        \e[032;1mCONTACT SUPPORT Telegram @aliyahaura02 SMS/WA 089697708638\e[0m"
echo "----------------------------------------------------------------"
echo ""

cd ~/

