#!/bin/bash

disable-user-expire
clear

echo -e "----------------------\e[032;1mDAFTAR AKUN SSH EXPIRE\e[0m----------------------"
echo -e "                       \e[032;1mALL SUPPORTED ALIYA HAURA\e[0m"
echo -e "                 \e[032;1mhttps://www.facebook.com/aliyahaura02\e[0m"
echo -e "        \e[032;1mCONTACT SUPPORT Telegram @aliyahaura02 SMS/WA 089697708638\e[0m"
echo ""

cat /root/expireduser.txt
echo ""

cd ~/

